
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubecarrier:e2e-clusterrole
rules:
- apiGroups:
  - "test.kubecarrier.io"
  - "fake.kubecarrier.io"
  - "scenarios-simple.test.kubecarrier.io"
  resources:
  - '*'
  verbs:
  - '*'
