
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.2.2
  creationTimestamp: null
  name: jokes.e2e.kubecarrier.io
spec:
  additionalPrinterColumns:
  - JSONPath: .status.selectedJoke.text
    name: Text
    type: date
  - JSONPath: .status.phase
    name: Status
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: e2e.kubecarrier.io
  names:
    kind: Joke
    listKind: JokeList
    plural: jokes
    singular: joke
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Joke is core element in joke generation operator
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: JokeSpec defines the desired state of Joke
          properties:
            jokeDatabase:
              description: JokeDatabase specifies all known jokes
              items:
                description: JokeCRDConfiguration holds static type information for
                  the Joke instance.
                properties:
                  text:
                    description: Text of the joke
                    type: string
                  type:
                    description: Type of the Joke
                    type: string
                required:
                - text
                - type
                type: object
              type: array
          type: object
        status:
          description: JokeStatus defines the observed state of Joke
          properties:
            conditions:
              description: Conditions is a list of all conditions this Joke is in.
              items:
                description: JokeCondition contains details for the current condition
                  of this Joke.
                properties:
                  lastTransitionTime:
                    description: LastTransitionTime is the last time the condition
                      transit from one status to another.
                    format: date-time
                    type: string
                  message:
                    description: Message is the human readable message indicating
                      details about last transition.
                    type: string
                  reason:
                    description: Reason is the (brief) reason for the condition's
                      last transition.
                    type: string
                  status:
                    description: Status of the condition, one of ('True', 'False',
                      'Unknown').
                    type: string
                  type:
                    description: Type of the condition, currently ('Ready').
                    type: string
                required:
                - lastTransitionTime
                - message
                - reason
                - status
                - type
                type: object
              type: array
            observedGeneration:
              description: The most recent generation observed by the controller.
              format: int64
              type: integer
            phase:
              description: Phase represents the current lifecycle state of this object
                consider this field DEPRECATED, it will be removed as soon as there
                is a mechanism to map conditions to a string when printing the property
                is only present for display purposes, for everything else use conditions
              type: string
            selectedJoke:
              description: Selected joke represent currently selected joke
              properties:
                text:
                  description: Text of the joke
                  type: string
                type:
                  description: Type of the Joke
                  type: string
              required:
              - text
              - type
              type: object
          required:
          - selectedJoke
          type: object
      type: object
  version: v1alpha2
  versions:
  - name: v1alpha2
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
