
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.2.9
  creationTimestamp: null
  name: customresourcediscoverysets.kubecarrier.io
spec:
  group: kubecarrier.io
  names:
    categories:
    - all
    - kubecarrier-provider
    kind: CustomResourceDiscoverySet
    listKind: CustomResourceDiscoverySetList
    plural: customresourcediscoverysets
    shortNames:
    - crdisset
    singular: customresourcediscoveryset
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.crd.name
      name: CustomResourceDefinition
      type: string
    - jsonPath: .status.phase
      name: Status
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: "CustomResourceDiscoverySet manages multiple CustomResourceDiscovery
          objects for a set of ServiceClusters. \n **Example** ```yaml apiVersion:
          kubecarrier.io/v1alpha1 kind: CustomResourceDiscoverySet metadata:   name:
          couchdb spec:   crd:     name: couchdbs.couchdb.io   serviceClusterSelector:
          {} ```"
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: CustomResourceDiscoverySetSpec describes the desired state
              of a CustomResourceDiscoverySet.
            properties:
              crd:
                description: CRD references a CustomResourceDefinition within the
                  ServiceCluster.
                properties:
                  name:
                    minLength: 1
                    type: string
                required:
                - name
                type: object
              kindOverride:
                description: KindOverride overrides the kind of the discovered CRD.
                type: string
              serviceClusterSelector:
                description: ServiceClusterSelector references a set of ServiceClusters
                  to search the CustomResourceDefinition on.
                properties:
                  matchExpressions:
                    description: matchExpressions is a list of label selector requirements.
                      The requirements are ANDed.
                    items:
                      description: A label selector requirement is a selector that
                        contains values, a key, and an operator that relates the key
                        and values.
                      properties:
                        key:
                          description: key is the label key that the selector applies
                            to.
                          type: string
                        operator:
                          description: operator represents a key's relationship to
                            a set of values. Valid operators are In, NotIn, Exists
                            and DoesNotExist.
                          type: string
                        values:
                          description: values is an array of string values. If the
                            operator is In or NotIn, the values array must be non-empty.
                            If the operator is Exists or DoesNotExist, the values
                            array must be empty. This array is replaced during a strategic
                            merge patch.
                          items:
                            type: string
                          type: array
                      required:
                      - key
                      - operator
                      type: object
                    type: array
                  matchLabels:
                    additionalProperties:
                      type: string
                    description: matchLabels is a map of {key,value} pairs. A single
                      {key,value} in the matchLabels map is equivalent to an element
                      of matchExpressions, whose key field is "key", the operator
                      is "In", and the values array contains only "value". The requirements
                      are ANDed.
                    type: object
                type: object
              webhookStrategy:
                default: None
                description: 'WebhookStrategy configs the webhooks of the CRDs which
                  are registered in the management cluster by this CustomResourceDiscoverySet.
                  There are two possible values for this configuration {None (by default),
                  ServiceCluster} None (by default): Webhook will only check if there
                  is an available ServiceClusterAssignment in the current Namespace.
                  ServiceCluster: Webhook will call webhooks of the CRD in the ServiceCluster
                  with dry-run flag.'
                enum:
                - None
                - ServiceCluster
                type: string
            required:
            - crd
            - serviceClusterSelector
            type: object
          status:
            description: CustomResourceDiscoverySetStatus represents the observed
              state of a CustomResourceDiscoverySet.
            properties:
              conditions:
                description: Conditions is a list of all conditions this CustomResourceDiscovery
                  is in.
                items:
                  description: CustomResourceDiscoverySetCondition contains details
                    for the current condition of this CustomResourceDiscoverySet.
                  properties:
                    lastTransitionTime:
                      description: LastTransitionTime is the last time the condition
                        transit from one status to another.
                      format: date-time
                      type: string
                    message:
                      description: Message is the human readable message indicating
                        details about last transition.
                      type: string
                    reason:
                      description: Reason is the (brief) reason for the condition's
                        last transition.
                      type: string
                    status:
                      description: Status of the condition, one of ('True', 'False',
                        'Unknown').
                      type: string
                    type:
                      description: Type of the condition, currently ('Ready').
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              managementClusterCRDs:
                description: ManagementClusterCRDs contains the CRDs information that
                  created by the CustomResourceDiscovery objects of this CustomResourceDiscoverySet.
                items:
                  description: CustomResourceDiscoverySetCRDReference references a
                    discovered CustomResourceDefinition.
                  properties:
                    crd:
                      description: ObjectReference describes the link to another object
                        in the same Namespace.
                      properties:
                        name:
                          minLength: 1
                          type: string
                      required:
                      - name
                      type: object
                    serviceCluster:
                      description: ObjectReference describes the link to another object
                        in the same Namespace.
                      properties:
                        name:
                          minLength: 1
                          type: string
                      required:
                      - name
                      type: object
                  required:
                  - crd
                  - serviceCluster
                  type: object
                type: array
              observedGeneration:
                description: The most recent generation observed by the controller.
                format: int64
                type: integer
              phase:
                description: DEPRECATED. Phase represents the current lifecycle state
                  of this object consider this field DEPRECATED, it will be removed
                  as soon as there is a mechanism to map conditions to a string when
                  printing the property is only present for display purposes, for
                  everything else use conditions
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
