
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-catalog-kubecarrier-io-v1alpha1-account
  failurePolicy: Fail
  name: vaccount.kubecarrier.io
  rules:
  - apiGroups:
    - catalog.kubecarrier.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - accounts
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-catalog-kubecarrier-io-v1alpha1-catalogentry
  failurePolicy: Fail
  name: vcatalogentry.kubecarrier.io
  rules:
  - apiGroups:
    - catalog.kubecarrier.io
    apiVersions:
    - v1alpha1
    operations:
    - UPDATE
    resources:
    - catalogentries
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-kubecarrier-io-v1alpha1-customresourcediscovery
  failurePolicy: Fail
  name: vcustomresourcediscovery.kubecarrier.io
  rules:
  - apiGroups:
    - kubecarrier.io
    apiVersions:
    - v1alpha1
    operations:
    - UPDATE
    resources:
    - customresourcediscoveries
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-catalog-kubecarrier-io-v1alpha1-derivedcustomresource
  failurePolicy: Fail
  name: vderivedcustomresource.kubecarrier.io
  rules:
  - apiGroups:
    - catalog.kubecarrier.io
    apiVersions:
    - v1alpha1
    operations:
    - UPDATE
    resources:
    - derivedcustomresources
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-catalog-kubecarrier-io-v1alpha1-offering
  failurePolicy: Fail
  name: voffering.kubecarrier.io
  rules:
  - apiGroups:
    - catalog.kubecarrier.io
    apiVersions:
    - v1alpha1
    operations:
    - UPDATE
    resources:
    - offerings
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-catalog-kubecarrier-io-v1alpha1-provider
  failurePolicy: Fail
  name: vprovider.kubecarrier.io
  rules:
  - apiGroups:
    - catalog.kubecarrier.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - providers
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-kubecarrier-io-v1alpha1-servicecluster
  failurePolicy: Fail
  name: vservicecluster.kubecarrier.io
  rules:
  - apiGroups:
    - kubecarrier.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - serviceclusters
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-kubecarrier-io-v1alpha1-serviceclusterassignment
  failurePolicy: Fail
  name: vserviceclusterassignment.kubecarrier.io
  rules:
  - apiGroups:
    - kubecarrier.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - serviceclusterassignments
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-catalog-kubecarrier-io-v1alpha1-serviceclusterreference
  failurePolicy: Fail
  name: vserviceclusterreference.kubecarrier.io
  rules:
  - apiGroups:
    - catalog.kubecarrier.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - serviceclusterreferences
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-catalog-kubecarrier-io-v1alpha1-tenant
  failurePolicy: Fail
  name: vtenant.kubecarrier.io
  rules:
  - apiGroups:
    - catalog.kubecarrier.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - tenants
